# -*- coding: utf-8 -*-
"""student-marks-analyzer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RUXLjEa0mND46UQdhOTW-fBZ2TsmyONE
"""

# asking user input for the four course names
s1 = input("Please enter your first course's name: ")
s2 = input("Please enter your second course's name: ")
s3 = input("Please enter your third course's name: ")
s4 = input("Please enter your fourth course's name: ")
# asking user input for respective marks scored in each subject
subjects = [[s1, s2, s3, s4]]
def grade(subject):
  y = True
  while y==True:
    grade = input(f"Please enter your {subject} marks out of 100:")
    try:
      float(grade) #converting user input from a string to float value
      grade = float(grade)
      if grade <=100:
        y = False
    except:
      print("Please make sure to enter a valid number") #error handling in case of invalid input
  return grade
g1 = grade(s1)
g2 = grade(s2)
g3 = grade(s3)
g4 = grade(s4)

# calculating the total marks and average marks.
total = g1 + g2 + g3 + g4
average = total / 4
print(f"Total Marks = {total} \nYour Average = {average}")

# generating a marksheet table
import pandas as pd
data = [[g1, g2, g3, g4]]
df = pd.DataFrame(data,
                  index=["marks"],
                  columns = subjects)
print(df)

# finding the strongest and the weakest subjects.
grades = {subjects[0][0]:data[0][0], subjects[0][1]:data[0][1], subjects[0][2]:data[0][2], subjects[0][3]:data[0][3]}

strongest = max(grades, key=grades.get)
weakest = min(grades, key=grades.get)
print(f"Your strongest subject is {strongest} and your weakest subject is {weakest}.")

# generating study recommendation.
recommendation = f"Focus on {weakest} the most."
print(recommendation)

# downloading the report as a .txt file.
f = open("myreport.txt", "w")
with open("myreport.txt", "a") as f:
  f.write(f"Grades: {grades} \nAverage Marks: {average}\nTotal Marks: {total}\nStrongest Subject: {strongest}\nWeakest Subject: {weakest}\nRecommendation: {recommendation}")